import { IDataBaseRepository } from "../i-data-base-repository"

class InMemoryDataBaseRepository implements IDataBaseRepository{
    public schema = '{"customers":["id","company","last_name","first_name","email_address","job_title","business_phone","home_phone","mobile_phone","fax_number","address","city","state_province","zip_postal_code","country_region","web_page","notes","attachments"],"employee_privileges":["employee_id","privilege_id"],"employees":["id","company","last_name","first_name","email_address","job_title","business_phone","home_phone","mobile_phone","fax_number","address","city","state_province","zip_postal_code","country_region","web_page","notes","attachments"],"inventory_transaction_types":["id","type_name"],"inventory_transactions":["id","transaction_type","transaction_created_date","transaction_modified_date","product_id","quantity","purchase_order_id","customer_order_id","comments"],"invoices":["id","order_id","invoice_date","due_date","tax","shipping","amount_due"],"order_details":["id","order_id","product_id","quantity","unit_price","discount","status_id","date_allocated","purchase_order_id","inventory_id"],"order_details_status":["id","status_name"],"orders":["id","employee_id","customer_id","order_date","shipped_date","shipper_id","ship_name","ship_address","ship_city","ship_state_province","ship_zip_postal_code","ship_country_region","shipping_fee","taxes","payment_type","paid_date","notes","tax_rate","tax_status_id","status_id"],"orders_status":["id","status_name"],"orders_tax_status":["id","tax_status_name"],"privileges":["id","privilege_name"],"products":["supplier_ids","id","product_code","product_name","description","standard_cost","list_price","reorder_level","target_level","quantity_per_unit","discontinued","minimum_reorder_quantity","category","attachments"],"purchase_order_details":["id","purchase_order_id","product_id","quantity","unit_cost","date_received","posted_to_inventory","inventory_id"],"purchase_order_status":["id","status"],"purchase_orders":["id","supplier_id","created_by","submitted_date","creation_date","status_id","expected_date","shipping_fee","taxes","payment_date","payment_amount","payment_method","notes","approved_by","approved_date","submitted_by"],"sales_reports":["group_by","display","title","filter_row_source","default"],"shippers":["id","company","last_name","first_name","email_address","job_title","business_phone","home_phone","mobile_phone","fax_number","address","city","state_province","zip_postal_code","country_region","web_page","notes","attachments"],"strings":["string_id","string_data"],"suppliers":["id","company","last_name","first_name","email_address","job_title","business_phone","home_phone","mobile_phone","fax_number","address","city","state_province","zip_postal_code","country_region","web_page","notes","attachments"]}'

    async showTablesEstructure() {
      return this.schema
    }
  
}

export {InMemoryDataBaseRepository}